name: "🐛 Bug Report"
description: "Report a bug or unexpected behavior"
title: "[BUG] "
labels: ["bug"]
body:
  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      options:
        - "P0 - Critical (system down)"
        - "P1 - High (major feature broken)"
        - "P2 - Medium (feature partially broken)"
        - "P3 - Low (minor issue)"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "A clear description of the bug"
      placeholder: "What happened?"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What should have happened?"
      placeholder: "What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "How can we reproduce this?"
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "System info, versions, etc."
      placeholder: |
        - OS: macOS 14.0
        - Node: 20.10.0
        - Browser: Chrome 120

  - type: textarea
    id: logs
    attributes:
      label: "Logs / Screenshots"
      description: "Any relevant logs or screenshots"
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: "Any other relevant information"
