name: "📋 Task"
description: "Create a development task"
title: "[TASK] "
labels: ["task"]
body:
  - type: dropdown
    id: type
    attributes:
      label: "Task Type"
      options:
        - "Feature Implementation"
        - "Bug Fix"
        - "Refactoring"
        - "Documentation"
        - "Testing"
        - "Infrastructure"
        - "Research"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - "P0 - Critical"
        - "P1 - High"
        - "P2 - Medium"
        - "P3 - Low"
    validations:
      required: true

  - type: input
    id: estimate
    attributes:
      label: "Estimate"
      description: "Story points or time estimate"
      placeholder: "3 points / 4 hours"

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "What needs to be done?"
      placeholder: "Implement the user authentication flow..."
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: "Acceptance Criteria"
      description: "How do we know this is done?"
      placeholder: |
        - [ ] User can log in with email/password
        - [ ] Session is created
        - [ ] Redirect to dashboard
    validations:
      required: true

  - type: textarea
    id: technical
    attributes:
      label: "Technical Notes"
      description: "Implementation details, dependencies"
      placeholder: |
        - Files to modify: src/auth/*
        - Dependencies: passport, bcrypt
        - Related: #123

  - type: input
    id: parent
    attributes:
      label: "Parent Issue"
      description: "Epic or parent issue number"
      placeholder: "#42"
