# PAF Sprint Metrics Workflow
# Generates sprint metrics when a milestone is closed

name: PAF Sprint Metrics

on:
  milestone:
    types: [closed]
  workflow_dispatch:
    inputs:
      milestone_number:
        description: 'Milestone number to generate metrics for'
        required: true
        type: number

jobs:
  generate-metrics:
    name: Generate Sprint Metrics
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Generate Sprint Metrics Report
        uses: actions/github-script@v7
        with:
          script: |
            const milestoneNumber = context.payload.milestone?.number || 
                                   ${{ github.event.inputs.milestone_number || 0 }};
            
            if (!milestoneNumber) {
              console.log('No milestone specified');
              return;
            }
            
            // Get milestone details
            const { data: milestone } = await github.rest.issues.getMilestone({
              owner: context.repo.owner,
              repo: context.repo.repo,
              milestone_number: milestoneNumber
            });
            
            // Get all issues in milestone
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              milestone: milestoneNumber,
              state: 'all',
              per_page: 100
            });
            
            // Calculate metrics
            const closedIssues = issues.filter(i => i.state === 'closed' && !i.pull_request);
            const openIssues = issues.filter(i => i.state === 'open' && !i.pull_request);
            const prs = issues.filter(i => i.pull_request);
            
            // Count by priority
            const byPriority = {
              P0: issues.filter(i => i.labels.some(l => l.name === 'P0')).length,
              P1: issues.filter(i => i.labels.some(l => l.name === 'P1')).length,
              P2: issues.filter(i => i.labels.some(l => l.name === 'P2')).length,
              P3: issues.filter(i => i.labels.some(l => l.name === 'P3')).length
            };
            
            // Count by category
            const categories = ['security', 'performance', 'ux', 'accessibility', 'tech-debt', 'documentation'];
            const byCategory = {};
            for (const cat of categories) {
              byCategory[cat] = issues.filter(i => 
                i.labels.some(l => l.name === cat)
              ).length;
            }
            
            // Count agent-generated
            const agentGenerated = issues.filter(i => 
              i.labels.some(l => l.name === '🤖 agent')
            ).length;
            
            // Generate report
            const completionRate = issues.length > 0 
              ? Math.round((closedIssues.length / (closedIssues.length + openIssues.length)) * 100)
              : 0;
            
            const report = `# 📊 Sprint Metrics: ${milestone.title}

## Summary

| Metric | Value |
|--------|-------|
| **Total Issues** | ${issues.length - prs.length} |
| **Completed** | ${closedIssues.length} |
| **Remaining** | ${openIssues.length} |
| **Completion Rate** | ${completionRate}% |
| **PRs Merged** | ${prs.filter(p => p.state === 'closed').length} |

## By Priority

| Priority | Count | Closed |
|----------|-------|--------|
| 🔴 P0 | ${byPriority.P0} | ${issues.filter(i => i.state === 'closed' && i.labels.some(l => l.name === 'P0')).length} |
| 🟠 P1 | ${byPriority.P1} | ${issues.filter(i => i.state === 'closed' && i.labels.some(l => l.name === 'P1')).length} |
| 🟡 P2 | ${byPriority.P2} | ${issues.filter(i => i.state === 'closed' && i.labels.some(l => l.name === 'P2')).length} |
| 🟢 P3 | ${byPriority.P3} | ${issues.filter(i => i.state === 'closed' && i.labels.some(l => l.name === 'P3')).length} |

## By Category

| Category | Count |
|----------|-------|
| 🔒 Security | ${byCategory.security || 0} |
| ⚡ Performance | ${byCategory.performance || 0} |
| 🎨 UX | ${byCategory.ux || 0} |
| 🔧 Tech Debt | ${byCategory['tech-debt'] || 0} |
| 📚 Documentation | ${byCategory.documentation || 0} |

## Agent Contributions

- **Agent-Generated Issues:** ${agentGenerated}
- **Percentage of Total:** ${issues.length > 0 ? Math.round((agentGenerated / issues.length) * 100) : 0}%

## Timeline

- **Sprint Start:** ${milestone.created_at ? new Date(milestone.created_at).toLocaleDateString() : 'N/A'}
- **Sprint End:** ${milestone.closed_at ? new Date(milestone.closed_at).toLocaleDateString() : 'N/A'}
- **Due Date:** ${milestone.due_on ? new Date(milestone.due_on).toLocaleDateString() : 'Not set'}

---
_Generated by PAF Sprint Metrics Action_
`;

            // Create summary issue
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[AGG] Sprint Metrics: ${milestone.title}`,
              body: report,
              labels: ['retrospective', '📋 george']
            });
            
            console.log('Sprint metrics report created successfully');
