#!/bin/bash
# PAF GitHub Setup - Labels
# Creates all PAF labels in the repository
# Usage: ./setup-labels.sh [--repo owner/repo]

# set -e removed - Labels may already exist

# Determine repository
if [ -n "$1" ] && [ "$1" == "--repo" ]; then
    REPO="$2"
else
    REPO=$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null)
fi

if [ -z "$REPO" ]; then
    echo "❌ No repository found. Use --repo owner/repo"
    exit 1
fi

echo "📋 Creating PAF labels for: $REPO"
echo ""

# Counter
CREATED=0
UPDATED=0
FAILED=0

create_label() {
    local name="$1"
    local color="$2"
    local desc="$3"
    
    if gh label create "$name" --repo "$REPO" --color "$color" --description "$desc" --force 2>/dev/null; then
        echo "  ✓ $name"
        ((CREATED++))
    else
        echo "  ✗ $name (Error)"
        ((FAILED++))
    fi
}

echo "=== Typ Labels ==="
create_label "bug" "d73a4a" "Something isn't working"
create_label "feature" "a2eeef" "New feature or request"
create_label "finding" "7057ff" "Agent-generated finding"
create_label "task" "fef2c0" "Implementation task"
create_label "adr" "0075ca" "Architecture Decision Record"
create_label "incident" "b60205" "Production incident"
create_label "epic" "3e4b9e" "Large feature grouping"
create_label "research" "c5def5" "Research or investigation"

echo ""
echo "=== Priority Labels ==="
create_label "P0" "b60205" "🔴 Critical - Fix immediately"
create_label "P1" "d93f0b" "🟠 High - This sprint"
create_label "P2" "fbca04" "🟡 Medium - Next sprint"
create_label "P3" "0e8a16" "🟢 Low - Backlog"

echo ""
echo "=== Phase Labels ==="
create_label "discovery" "c5def5" "Discovery phase"
create_label "planning" "bfd4f2" "Planning phase"
create_label "implementation" "d4c5f9" "Implementation phase"
create_label "review" "f9d0c4" "Review phase"
create_label "deployment" "c2e0c6" "Deployment phase"
create_label "operations" "fef2c0" "Operations phase"

echo ""
echo "=== Agent Labels (Generisch) ==="
create_label "🤖 agent" "7057ff" "Auto-generated by PAF agent"

echo ""
echo "=== Agent Labels (Orchestration) ==="
create_label "🎪 cto" "5a32a3" "CTO / Orchestrator"

echo ""
echo "=== Agent Labels (Perspective) ==="
create_label "🔒 alex" "d73a4a" "Security Analyst"
create_label "⚡ emma" "fbca04" "Performance Engineer"
create_label "🎨 sam" "a2eeef" "UX Designer"
create_label "🔀 david" "0075ca" "Solutions Architect"
create_label "🔧 max" "5319e7" "Maintainability Expert"
create_label "♿ luna" "006b75" "Accessibility Expert"
create_label "💰 tom" "0e8a16" "FinOps Engineer"
create_label "🎯 nina" "d93f0b" "Triage Lead"
create_label "📚 leo" "bfd4f2" "Documentation Lead"
create_label "💡 ava" "fef2c0" "Innovation Lead"

echo ""
echo "=== Agent Labels (Discovery) ==="
create_label "📝 maya" "c5def5" "Product Manager"
create_label "🔬 iris" "c5def5" "Innovation Scout"
create_label "📊 ben" "c5def5" "Data Analyst"

echo ""
echo "=== Agent Labels (Planning) ==="
create_label "🏛️ sophia" "bfd4f2" "Software Architect"
create_label "👨‍💻 michael" "bfd4f2" "Tech Lead"
create_label "📅 kai" "bfd4f2" "Project Manager"

echo ""
echo "=== Agent Labels (Implementation) ==="
create_label "💻 sarah" "d4c5f9" "Lead Developer"
create_label "🔌 anna" "d4c5f9" "API Developer"
create_label "🧩 chris" "d4c5f9" "Frontend Developer"
create_label "🗄️ dan" "d4c5f9" "Backend Developer"
create_label "🧪 tina" "d4c5f9" "QA Engineer"

echo ""
echo "=== Agent Labels (Review) ==="
create_label "👀 rachel" "f9d0c4" "Review Lead"
create_label "📏 stan" "f9d0c4" "Standards Guard"
create_label "🔍 scanner" "f9d0c4" "Security Scanner"
create_label "⏱️ perf" "f9d0c4" "Performance Analyzer"

echo ""
echo "=== Agent Labels (Deployment) ==="
create_label "🚀 tony" "c2e0c6" "DevOps Engineer"
create_label "📦 rel" "c2e0c6" "Release Manager"
create_label "🔄 miggy" "c2e0c6" "Migration Lead"

echo ""
echo "=== Agent Labels (Operations) ==="
create_label "🚨 inci" "fef2c0" "Incident Commander"
create_label "📈 monitor" "fef2c0" "Monitoring Engineer"
create_label "💬 feedback" "fef2c0" "Feedback Collector"

echo ""
echo "=== Agent Labels (Retrospective) ==="
create_label "📋 george" "5319e7" "Scrum Master"
create_label "⚙️ otto" "5319e7" "Process Optimizer"
create_label "📖 docu" "5319e7" "Documentation Lead"

echo ""
echo "=== Agent Labels (Utility) ==="
create_label "🛠️ gideon" "000000" "GitHub Setup Agent"
create_label "🐛 bugfix" "d73a4a" "Bug Fixer Agent"
create_label "✅ validator" "0e8a16" "Validation Agent"

echo ""
echo "=== Category Labels ==="
create_label "security" "d73a4a" "Security related"
create_label "performance" "fbca04" "Performance related"
create_label "ux" "a2eeef" "User experience"
create_label "accessibility" "006b75" "Accessibility (a11y)"
create_label "architecture" "0075ca" "Architecture related"
create_label "documentation" "bfd4f2" "Documentation"
create_label "tech-debt" "5319e7" "Technical debt"
create_label "cost" "0e8a16" "Cost optimization"
create_label "testing" "d4c5f9" "Testing related"
create_label "infrastructure" "c2e0c6" "Infrastructure"

echo ""
echo "=== Status Labels ==="
create_label "blocked" "b60205" "Blocked by dependency"
create_label "needs-review" "fbca04" "Needs code review"
create_label "needs-info" "d876e3" "Needs more information"
create_label "ready" "0e8a16" "Ready for implementation"
create_label "wontfix" "ffffff" "Will not be fixed"
create_label "duplicate" "cfd3d7" "Duplicate of another issue"
create_label "stale" "ededed" "No recent activity"

echo ""
echo "════════════════════════════════════════════"
echo "✅ Labels created: $CREATED"
echo "❌ Errors: $FAILED"
echo "════════════════════════════════════════════"

# Verification
TOTAL=$(gh label list --repo "$REPO" --json name -q 'length')
echo "📊 Total labels in repo: $TOTAL"
