#!/bin/bash
# PAF GitHub Issue Templates Setup
# Creates Issue Templates in .github/ISSUE_TEMPLATE/ directory

# set -e removed

# Target directory
TEMPLATE_DIR=".github/ISSUE_TEMPLATE"
GITHUB_DIR=".github"

echo "📝 Creating PAF Issue Templates..."
echo ""

# Create directories
mkdir -p "$TEMPLATE_DIR"

echo "📦 Creating Issue Templates..."

# 1. Agent Finding Template
cat > "$TEMPLATE_DIR/agent-finding.yml" << 'EOF'
name: "🤖 Agent Finding"
description: "Finding generated by PAF agent"
title: "[PREFIX-XXX] "
labels: ["finding", "🤖 agent"]
body:
  - type: dropdown
    id: agent
    attributes:
      label: "Agent"
      description: "Which agent generated this finding?"
      options:
        - "🔒 Alex (Security)"
        - "⚡ Emma (Performance)"
        - "🎨 Sam (UX)"
        - "🔀 David (Scalability)"
        - "🔧 Max (Maintainability)"
        - "♿ Luna (Accessibility)"
        - "💰 Tom (Cost)"
        - "🎯 Nina (Triage)"
        - "📚 Leo (Documentation)"
        - "💡 Ava (Innovation)"
        - "🔍 Scanner (Security)"
        - "⏱️ Perf (Performance)"
        - "🧪 Tina (QA)"
        - "📏 Stan (Standards)"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      options:
        - "P0 - Critical (fix immediately)"
        - "P1 - High (this sprint)"
        - "P2 - Medium (next sprint)"
        - "P3 - Low (backlog)"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: "Category"
      options:
        - "security"
        - "performance"
        - "ux"
        - "accessibility"
        - "architecture"
        - "documentation"
        - "tech-debt"
        - "cost"
        - "testing"
    validations:
      required: true

  - type: textarea
    id: finding
    attributes:
      label: "Finding"
      description: "What was found?"
      placeholder: "Describe the finding in detail..."
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: "Location"
      description: "Where was this found?"
      placeholder: |
        File: src/auth/login.ts
        Line: 42-55
        Function: validateToken()

  - type: textarea
    id: evidence
    attributes:
      label: "Evidence"
      description: "Code snippets, logs, screenshots"
      render: shell

  - type: textarea
    id: recommendation
    attributes:
      label: "Recommendation"
      description: "How should this be fixed?"
      placeholder: |
        1. First step...
        2. Second step...
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: "References"
      description: "Related docs, CVEs, standards"
      placeholder: |
        - OWASP Top 10: A03
        - https://...
EOF
echo "  ✅ agent-finding.yml"

# 2. Bug Report Template
cat > "$TEMPLATE_DIR/bug-report.yml" << 'EOF'
name: "🐛 Bug Report"
description: "Report a bug or issue"
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "A clear description of the bug"
      placeholder: "What happened?"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "Steps to Reproduce"
      description: "How can we reproduce this?"
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What should have happened?"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "OS, Browser, Version, etc."
      placeholder: |
        - OS: macOS 14.0
        - Browser: Chrome 120
        - Version: 1.0.0

  - type: textarea
    id: logs
    attributes:
      label: "Logs/Screenshots"
      description: "Add any relevant logs or screenshots"
      render: shell

  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      options:
        - "P0 - Critical (system down)"
        - "P1 - High (major feature broken)"
        - "P2 - Medium (workaround exists)"
        - "P3 - Low (minor issue)"
EOF
echo "  ✅ bug-report.yml"

# 3. Feature Request Template
cat > "$TEMPLATE_DIR/feature-request.yml" << 'EOF'
name: "✨ Feature Request"
description: "Suggest a new feature"
title: "[FEATURE] "
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: "Problem Statement"
      description: "What problem does this solve?"
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
      description: "How would you like it to work?"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Any other solutions you've thought about?"

  - type: textarea
    id: context
    attributes:
      label: "Additional Context"
      description: "Any other context, mockups, or references"

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "How important is this to you?"
      options:
        - "Must have"
        - "Should have"
        - "Nice to have"
        - "Future consideration"
EOF
echo "  ✅ feature-request.yml"

# 4. Incident Template
cat > "$TEMPLATE_DIR/incident.yml" << 'EOF'
name: "🚨 Incident Report"
description: "Report a production incident"
title: "[INC] "
labels: ["incident", "P0"]
body:
  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      options:
        - "SEV1 - Critical (full outage)"
        - "SEV2 - Major (significant impact)"
        - "SEV3 - Minor (limited impact)"
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: "Impact"
      description: "Who/what is affected?"
      placeholder: |
        - Users affected: All/Some/Few
        - Features affected: ...
        - Revenue impact: Yes/No
    validations:
      required: true

  - type: textarea
    id: timeline
    attributes:
      label: "Timeline"
      description: "When did this start?"
      placeholder: |
        - First alert: 2024-01-15 10:30 UTC
        - First customer report: ...
    validations:
      required: true

  - type: textarea
    id: symptoms
    attributes:
      label: "Symptoms"
      description: "What are we seeing?"
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: "Current Mitigation"
      description: "What are we doing right now?"

  - type: textarea
    id: root-cause
    attributes:
      label: "Root Cause (if known)"
      description: "What caused this?"
EOF
echo "  ✅ incident.yml"

# 5. ADR Template
cat > "$TEMPLATE_DIR/adr.yml" << 'EOF'
name: "🏗️ Architecture Decision Record"
description: "Document an architecture decision"
title: "[ADR] "
labels: ["adr", "architecture"]
body:
  - type: input
    id: adr-number
    attributes:
      label: "ADR Number"
      placeholder: "ADR-001"
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: "Status"
      options:
        - "Proposed"
        - "Accepted"
        - "Deprecated"
        - "Superseded"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Context"
      description: "What is the issue we're addressing?"
    validations:
      required: true

  - type: textarea
    id: decision
    attributes:
      label: "Decision"
      description: "What is the change we're proposing?"
    validations:
      required: true

  - type: textarea
    id: consequences
    attributes:
      label: "Consequences"
      description: "What are the results of this decision?"
      placeholder: |
        Positive:
        - ...
        
        Negative:
        - ...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "What other options were evaluated?"
EOF
echo "  ✅ adr.yml"

# 6. Task Template
cat > "$TEMPLATE_DIR/task.yml" << 'EOF'
name: "📋 Task"
description: "Create a development task"
title: "[TASK] "
labels: ["task"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Task Description"
      description: "What needs to be done?"
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: "Acceptance Criteria"
      description: "How do we know it's done?"
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true

  - type: textarea
    id: technical
    attributes:
      label: "Technical Notes"
      description: "Implementation hints, dependencies"

  - type: dropdown
    id: estimate
    attributes:
      label: "Estimate"
      options:
        - "XS (< 1h)"
        - "S (1-4h)"
        - "M (1-2 days)"
        - "L (3-5 days)"
        - "XL (> 1 week)"

  - type: input
    id: parent
    attributes:
      label: "Parent Issue"
      description: "Epic or feature this belongs to"
      placeholder: "#123"
EOF
echo "  ✅ task.yml"

# 7. Retrospective Template
cat > "$TEMPLATE_DIR/retro.yml" << 'EOF'
name: "📊 Retrospective"
description: "Sprint retrospective summary"
title: "[RETRO] Sprint "
labels: ["retrospective"]
body:
  - type: input
    id: sprint
    attributes:
      label: "Sprint"
      placeholder: "Sprint 1 (2024-01-01 - 2024-01-14)"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: "Sprint Summary"
      description: "Key metrics and outcomes"
      placeholder: |
        - Velocity: X points
        - Completed: Y issues
        - Bugs found: Z
    validations:
      required: true

  - type: textarea
    id: went-well
    attributes:
      label: "What Went Well"
      description: "Things to continue"
      placeholder: |
        - ...
    validations:
      required: true

  - type: textarea
    id: improve
    attributes:
      label: "What Could Improve"
      description: "Things to change"
      placeholder: |
        - ...
    validations:
      required: true

  - type: textarea
    id: actions
    attributes:
      label: "Action Items"
      description: "Concrete next steps"
      placeholder: |
        - [ ] Action 1 (@owner)
        - [ ] Action 2 (@owner)
    validations:
      required: true
EOF
echo "  ✅ retro.yml"

# 8. Config (Template Chooser)
cat > "$TEMPLATE_DIR/config.yml" << 'EOF'
blank_issues_enabled: false
contact_links:
  - name: "📚 PAF Documentation"
    url: "https://github.com/crack00r/paf-framework"
    about: "Check the PAF Framework documentation"
EOF
echo "  ✅ config.yml"

# 9. Pull Request Template
cat > "$GITHUB_DIR/PULL_REQUEST_TEMPLATE.md" << 'EOF'
## Description

<!-- What does this PR do? -->

## Related Issues

<!-- Link related issues: Fixes #123, Relates to #456 -->

## Changes

<!-- List the changes made -->

- 
- 

## Testing

<!-- How was this tested? -->

- [ ] Unit tests added/updated
- [ ] Manual testing completed
- [ ] No testing needed (docs only)

## Checklist

- [ ] Code follows project style guidelines
- [ ] Self-review completed
- [ ] Documentation updated (if needed)
- [ ] No new warnings introduced

## Screenshots (if applicable)

<!-- Add screenshots for UI changes -->

---
_PR created following PAF Framework guidelines_
EOF
echo "  ✅ PULL_REQUEST_TEMPLATE.md"

echo ""
echo "✅ Issue Templates Setup completed!"
echo "   Created in: $TEMPLATE_DIR/"
echo "   PR Template: $GITHUB_DIR/PULL_REQUEST_TEMPLATE.md"
